[webservers]

web-1 ansible_host=89.169.138.55 fqdn=web-1.ru-central1.internal

web-2 ansible_host=51.250.93.215 fqdn=web-2.ru-central1.internal


[databases]

main ansible_host=89.169.140.152 fqdn=main.ru-central1.internal

replica ansible_host=62.84.113.57 fqdn=replica.ru-central1.internal


[storage]

storage ansible_host=89.169.154.54 fqdn=storage.ru-central1.internal
