[webservers]

web-1 ansible_host= fqdn=web-1.ru-central1.internal

web-2 ansible_host= fqdn=web-2.ru-central1.internal


[databases]

main ansible_host= fqdn=main.ru-central1.internal

replica ansible_host= fqdn=replica.ru-central1.internal


[storage]

storage ansible_host= fqdn=storage.ru-central1.internal
